"! <p class="shorttext synchronized" lang="en">abap2UI5 customer frontend extension - icons</p>
"!
"! The icons of the <em>my-icons</em> collection, one constant per
"! glyph. GENERATED by tools/font2js.mjs - run 'npm run font2js' after
"! changing fonts/MyCustomFontFamily.*.
"!
"! The collection is registered in the browser by
"! <em>z2ui5_ccc/fonts/MyCustomFontFamily.js</em>, which
"! <em>z2ui5_ccc/cc/Extension.js</em> hands to the UI5 IconPool - so a view
"! that uses one of these constants has to render the bootstrap element
"! first:
"!
"!   z2ui5_cl_ccc=&gt;render( page ).
"!   page-&gt;tag( `Button`
"!       )-&gt;a( n = `icon` v = z2ui5_if_ccc_icon=&gt;regal ).
"!
"! Without it the icon property holds a URI nothing resolves, and UI5 draws
"! NO glyph and logs nothing - see the note in cc/Extension.js on why the
"! registration happens in init( ) rather than after rendering.
"!
"! The constant names are the glyph names lower-cased; the values keep the
"! font's own spelling, which is what UI5 looks up and IS case sensitive.
INTERFACE z2ui5_if_ccc_icon
  PUBLIC.

  "! collection name - the host part of every URI below, and the name
  "! cc/Extension.js registers the font under
  CONSTANTS c_collection TYPE string VALUE `my-icons`.
  "! prefix every icon URI of this collection carries
  CONSTANTS c_uri_prefix TYPE string VALUE `sap-icon://my-icons/`.

  "! bestandsInfoHU (U+E900)
  CONSTANTS bestandsinfohu          TYPE string VALUE `sap-icon://my-icons/bestandsInfoHU`.
  "! bestandsInfoLager (U+E901)
  CONSTANTS bestandsinfolager       TYPE string VALUE `sap-icon://my-icons/bestandsInfoLager`.
  "! bestandsInfoMat (U+E902)
  CONSTANTS bestandsinfomat         TYPE string VALUE `sap-icon://my-icons/bestandsInfoMat`.
  "! bestandsInfoMat1 (U+E903)
  CONSTANTS bestandsinfomat1        TYPE string VALUE `sap-icon://my-icons/bestandsInfoMat1`.
  "! bewegungAbgeschlossen (U+E904)
  CONSTANTS bewegungabgeschlossen   TYPE string VALUE `sap-icon://my-icons/bewegungAbgeschlossen`.
  "! bewegungAbgeschlossen1 (U+E905)
  CONSTANTS bewegungabgeschlossen1  TYPE string VALUE `sap-icon://my-icons/bewegungAbgeschlossen1`.
  "! fordertechnikaufladen (U+E906)
  CONSTANTS fordertechnikaufladen   TYPE string VALUE `sap-icon://my-icons/fordertechnikaufladen`.
  "! fordertechnikentnehmen (U+E907)
  CONSTANTS fordertechnikentnehmen  TYPE string VALUE `sap-icon://my-icons/fordertechnikentnehmen`.
  "! kommisionierHUbeladen (U+E908)
  CONSTANTS kommisionierhubeladen   TYPE string VALUE `sap-icon://my-icons/kommisionierHUbeladen`.
  "! KommisionierHUentnehmen (U+E909)
  CONSTANTS kommisionierhuentnehmen TYPE string VALUE `sap-icon://my-icons/KommisionierHUentnehmen`.
  "! Lageraufgabequitiert (U+E90A)
  CONSTANTS lageraufgabequitiert    TYPE string VALUE `sap-icon://my-icons/Lageraufgabequitiert`.
  "! Lageraufgabequitiert1 (U+E90B)
  CONSTANTS lageraufgabequitiert1   TYPE string VALUE `sap-icon://my-icons/Lageraufgabequitiert1`.
  "! Lagerauslagern (U+E90C)
  CONSTANTS lagerauslagern          TYPE string VALUE `sap-icon://my-icons/Lagerauslagern`.
  "! Lagereinlagern (U+E90D)
  CONSTANTS lagereinlagern          TYPE string VALUE `sap-icon://my-icons/Lagereinlagern`.
  "! LKWausladen (U+E90E)
  CONSTANTS lkwausladen             TYPE string VALUE `sap-icon://my-icons/LKWausladen`.
  "! LKWbeladen (U+E90F)
  CONSTANTS lkwbeladen              TYPE string VALUE `sap-icon://my-icons/LKWbeladen`.
  "! Regal (U+E910)
  CONSTANTS regal                   TYPE string VALUE `sap-icon://my-icons/Regal`.
  "! Regal2 (U+E911)
  CONSTANTS regal2                  TYPE string VALUE `sap-icon://my-icons/Regal2`.
  "! Regal3 (U+E912)
  CONSTANTS regal3                  TYPE string VALUE `sap-icon://my-icons/Regal3`.
  "! Regal4 (U+E913)
  CONSTANTS regal4                  TYPE string VALUE `sap-icon://my-icons/Regal4`.
  "! Regal5 (U+E914)
  CONSTANTS regal5                  TYPE string VALUE `sap-icon://my-icons/Regal5`.
  "! Stapler (U+E915)
  CONSTANTS stapler                 TYPE string VALUE `sap-icon://my-icons/Stapler`.
  "! Staplereinlagern (U+E916)
  CONSTANTS staplereinlagern        TYPE string VALUE `sap-icon://my-icons/Staplereinlagern`.
  "! Staplerentnehmen (U+E917)
  CONSTANTS staplerentnehmen        TYPE string VALUE `sap-icon://my-icons/Staplerentnehmen`.
  "! StaplerInfo (U+E918)
  CONSTANTS staplerinfo             TYPE string VALUE `sap-icon://my-icons/StaplerInfo`.
  "! StaplerLogin (U+E919)
  CONSTANTS staplerlogin            TYPE string VALUE `sap-icon://my-icons/StaplerLogin`.
  "! StaplerLogout (U+E91A)
  CONSTANTS staplerlogout           TYPE string VALUE `sap-icon://my-icons/StaplerLogout`.
  "! StaplerLogout1 (U+E91B)
  CONSTANTS staplerlogout1          TYPE string VALUE `sap-icon://my-icons/StaplerLogout1`.
  "! umpacken (U+E91C)
  CONSTANTS umpacken                TYPE string VALUE `sap-icon://my-icons/umpacken`.
  "! umpacken1 (U+E91D)
  CONSTANTS umpacken1               TYPE string VALUE `sap-icon://my-icons/umpacken1`.

ENDINTERFACE.
